name: 'klaviyo_source_integration_tests'
version: '0.7.0'
config-version: 2
profile: 'integration_tests'


vars:
  klaviyo_campaign_identifier: "campaign"
  klaviyo_event_identifier: "event"
  klaviyo_flow_identifier: "flow"
  klaviyo_integration_identifier: "integration"
  klaviyo_person_identifier: "person"
  klaviyo_metric_identifier: "metric"
  klaviyo__event_pass_through_columns: []
  klaviyo__person_pass_through_columns: []
  klaviyo_schema: klaviyo_source_integration_tests_1

seeds:
  klaviyo_source_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    +column_types:
      _FIVETRAN_SYNCED: timestamp
    person:
      +column_types:
        PHONE_NUMBER: "{{ 'string' if target.type in ('bigquery', 'spark', 'databricks') else 'varchar' }}"
    flow:
      +enabled: "{{ true if target.type != 'snowflake' else false }}"
      +quote_columns: "{{ true if target.type == 'redshift' else false }}"